include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

variables:
  BUNDLE: 'org.gnome.Patterns.flatpak'

flatpak:
  extends: '.flatpak'
  variables:
    MANIFEST_PATH: 'org.gnome.Patterns.json'
    RUNTIME_REPO: 'https://nightly.gnome.org/gnome-nightly.flatpakrepo'
    FLATPAK_MODULE: 'patterns'
    APP_ID: 'org.gnome.Patterns'
