on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
name: "Flatpak Nightly"
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    timeout-minutes: 600
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64, aarch64]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Docker
      run: |
        dnf -y install docker
    - name: Setup QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        platforms: arm64
    - name: Prepare Runtime
      run: |
        flatpak --system install -y --noninteractive flathub org.freedesktop.Sdk.Extension.rust-nightly/${{ matrix.arch }}/21.08
        flatpak --system install -y --noninteractive flathub org.freedesktop.Sdk.Extension.llvm13/${{ matrix.arch }}/21.08
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      name: Build
      with:
        bundle: com.github.rafostar.Clapper.flatpak
        manifest-path: pkgs/flatpak/com.github.rafostar.Clapper-nightly.json
        repository-name: gnome-nightly
        repository-url: https://nightly.gnome.org/gnome-nightly.flatpakrepo
        cache-key: flatpak-builder-${{ github.sha }}-testing-${{ github.run_number }}
        arch: ${{ matrix.arch }}
